### ISSUE TITLE
Design and functionality of categories page

### ISSUE THREAD

**Issue by johnsonzsong** [cs210/Daimler#10]
- Figma link for designs (multiple iterations if needed)
- API calls to categories
- Connect functionality to interface

**Comment by johnsonzsong** [comment]
New categories design finished, with difficulty selection (all in Figma).
@pauanzaldo you can start dev based on this design for now

![image](https://user-images.githubusercontent.com/40360441/79048418-e901e280-7bea-11ea-873a-7c630b4c532f.png)
![image](https://user-images.githubusercontent.com/40360441/79048419-ec956980-7bea-11ea-9bd2-ea2c0de1d270.png)
![image](https://user-images.githubusercontent.com/40360441/79048420-eef7c380-7bea-11ea-8517-57dfb63d747c.png)
![image](https://user-images.githubusercontent.com/40360441/79048422-f15a1d80-7bea-11ea-9357-879102dc593a.png)
![image](https://user-images.githubusercontent.com/40360441/79048423-f3bc7780-7bea-11ea-99a6-60c2a5bd72b2.png)
![image](https://user-images.githubusercontent.com/40360441/79048428-f5863b00-7bea-11ea-9719-f51655c5dd7a.png)

**Comment by johnsonzsong** [comment]
@pauanzaldo I just made all the buttons update on click, and also fixed the styling to reflect Figma specs. Also, made sure the overflow was scrollable. Screenshots of function (running on dev env)!:

![image](https://user-images.githubusercontent.com/40360441/79058805-7c193780-7c40-11ea-88c5-60c269439430.png)
![image](https://user-images.githubusercontent.com/40360441/79058810-89362680-7c40-11ea-976f-21cace7c6106.png)

**Comment by pauanzaldo** [comment]
This is looking so good! I'm glad it's connected from the main page and the Figma design matches the interface. Moving forward, we just need to have the "Next" button for the difficulty

**Comment by pauanzaldo** [comment]
<img width="1060" alt="Screen Shot 2020-04-12 at 7 18 23 PM" src="https://user-images.githubusercontent.com/22547339/79083286-fd310700-7cf2-11ea-8418-24c0ecc172ee.png">

Difficulty Screen is implemented!

Now, we need to do 2 things:

1. The floating button that would send the user to difficulty screen,

2. We need to fix the spacing between the [Easy Medium Hard] buttons and [Start] (on the difficulty screen) 

We're on a good track!

**Comment by johnsonzsong** [comment]
I added the button to move from categories to difficulty screen. Now, we have to hook it up to the API calls to get the correct questions/categories.

**Comment by pauanzaldo** [comment]
Functionally of categories accomplished!!

**Comment by johnsonzsong** [comment]
@pauanzaldo  I'm gonna close this issue because we've finished all the functionality and design and implementation of the categories -> questions -> feedback flow. I'm going to open another issue to put our work onto the live server.
