### ISSUE TITLE
Design score leaderboard flow

### ISSUE THREAD

**Issue by johnsonzsong** [cs210/Daimler#18]
- screenshots uploaded when finished
- link to figma when finished

**Comment by johnsonzsong** [comment]
@pauanzaldo  just a reminder to make sure the screens are connected correctly in the Figma prototype too whenever you get to that point! 😄

**Comment by pauanzaldo** [comment]
![image](https://user-images.githubusercontent.com/22547339/79764617-323ceb00-82eb-11ea-838d-5a5dd199c84a.png)

This is what the leaderboard looks like, and it's connected to Figma! @johnsonzsong  we just need to have your screenshot and we can then close the issue

**Comment by johnsonzsong** [comment]
@pauanzaldo I already uploaded my screenshots and Figma link for the user selection screens and closed that issue, so I'm going to close this issue now
