### ISSUE TITLE
Design Multiple Choice Question/Answer Screens

### ISSUE THREAD

**Issue by pauanzaldo** [cs210/Daimler#6]
https://www.figma.com/file/wgkf0Bb5YrHXKGYLv3OfVI/CS210-Cabana-Trivia-Master?node-id=0%3A1

**Comment by johnsonzsong** [comment]
Why is this called 'Design categories'? I did the categories screens

**Comment by pauanzaldo** [comment]
Sorry if not clear -- I meant the multiple choice options for the categories (Science and FIlm).
